name: ❓ Question
description: Ask for help or clarify features.
title: "[Q]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      placeholder: Describe what you need clarification on...
    validations:
      required: true
