name: Windows Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Run PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed --add-data "src/resources;src/resources" --name "SmartChess" main.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: smart-chess-win-x64
        path: dist/SmartChess/
